select max(date) from dbt_dev_staging.stg_stockprice;

-- Confirm the stored procedure exists
SHOW PROCEDURES LIKE 'STOCK_SPROC' IN SCHEMA DBT_STOCKPROJECT.DBT_DEV_STAGING;

-- Confirm the task exists
SHOW TASKS LIKE 'STOCK_SPROC_DAILY_TASK' IN SCHEMA DBT_STOCKPROJECT.DBT_DEV_STAGING;

SELECT CURRENT_ACCOUNT(), CURRENT_REGION();

select current_user();

DESC USER JDSMITHWES;

ALTER USER JDSMITHWES SET MINS_TO_BYPASS_MFA = 60;

ALTER USER JDSMITHWES SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuI2uozsyjNRRViyzVfNtOaPkPy2/soeLl3yLm8tnwHph9Rlm9GxFrFAohPzAdOmmsEz42gvajie31XTcm+4gDxP+SJyNTR46d0K9WpHwSObmwP6bobx7eKffdkc51Bvgt4/+hCCd3QkFU6noF+sMadWBHL/QPAdzaGoR8hk68r18LpCbnyGIJObM12nEWGDZWYp32AoqvOBYaKNaiU+NeHuVcya1xfp4o84M5Ss2UKhvwVCLDf+DyNmktKNEUIbG91yBk+1PfBIVI3H+xInblYTLalfPHvIAcrHMXM9SuS/eRTPU5ZtwwVxJ4Tbl553uA+ki6PDcQRBuLo7Bh8a9pQIDAQAB';

-- Check who owns the schema
SHOW SCHEMAS IN DATABASE DBT_STOCKPROJECT;

-- Grant ACCOUNTADMIN full access (run as SYSADMIN or schema owner)
USE ROLE SYSADMIN;
GRANT USAGE ON DATABASE DBT_STOCKPROJECT TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA DBT_STOCKPROJECT.DBT_DEV_STAGING TO ROLE ACCOUNTADMIN;
GRANT CREATE STAGE ON SCHEMA DBT_STOCKPROJECT.DBT_DEV_STAGING TO ROLE ACCOUNTADMIN;
GRANT CREATE PROCEDURE ON SCHEMA DBT_STOCKPROJECT.DBT_DEV_STAGING TO ROLE ACCOUNTADMIN;
GRANT CREATE TASK ON SCHEMA DBT_STOCKPROJECT.DBT_DEV_STAGING TO ROLE ACCOUNTADMIN;

CALL STOCK_SPROC('2026-02-20', '2026-04-04');

CREATE OR REPLACE SECRET DBT_STOCKPROJECT.DBT_DEV_STAGING.ALPHAVANTAGE_SECRET
  TYPE = GENERIC_STRING
  SECRET_STRING = 'NY03HQLBAOIVQ6AF';

CREATE OR REPLACE NETWORK RULE DBT_STOCKPROJECT.DBT_DEV_STAGING.ALPHAVANTAGE_NETWORK_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('www.alphavantage.co');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION ALPHAVANTAGE_ACCESS_INTEGRATION
  ALLOWED_NETWORK_RULES = (DBT_STOCKPROJECT.DBT_DEV_STAGING.ALPHAVANTAGE_NETWORK_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (DBT_STOCKPROJECT.DBT_DEV_STAGING.ALPHAVANTAGE_SECRET)
  ENABLED = TRUE;

CREATE OR REPLACE PROCEDURE DBT_STOCKPROJECT.DBT_DEV_STAGING.STOCK_SPROC(
  "ARG1" VARCHAR DEFAULT NULL, "ARG2" VARCHAR DEFAULT NULL
)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python','pandas','requests','cloudpickle==3.1.1')
HANDLER = 'Snowpark_API_Script.run_as_sproc'
IMPORTS = ('@DBT_STOCKPROJECT.DBT_DEV_STAGING.STOCK_SPROC_STAGE/STOCK_SPROC/Snowpark_API_Script.py')
EXTERNAL_ACCESS_INTEGRATIONS = (ALPHAVANTAGE_ACCESS_INTEGRATION)
SECRETS = ('alphavantage_api_key' = DBT_STOCKPROJECT.DBT_DEV_STAGING.ALPHAVANTAGE_SECRET)
COMMENT = 'Fetches AlphaVantage daily stock data and appends to target table.'
EXECUTE AS OWNER;

-- Grant the role running the procedure permission to use the secret and integration
GRANT USAGE ON SECRET DBT_STOCKPROJECT.DBT_DEV_STAGING.ALPHAVANTAGE_SECRET TO ROLE DBT_ROLE;
GRANT USAGE ON INTEGRATION ALPHAVANTAGE_ACCESS_INTEGRATION TO ROLE DBT_ROLE;

SHOW SECRETS IN SCHEMA DBT_STOCKPROJECT.DBT_DEV_STAGING;


USE ROLE ACCOUNTADMIN;
SHOW SECRETS IN ACCOUNT;

-- Test with explicit date range (small, fast)
CALL DBT_STOCKPROJECT.DBT_DEV_STAGING.STOCK_SPROC('2026-02-20', '2026-04-04');

-- Check rows landed
SELECT ticker, date, COUNT(*) 
FROM DBT_STOCKPROJECT.DBT_DEV_STAGING.STG_STOCKPRICE
WHERE date BETWEEN '2026-02-20' AND '2026-04-04'
GROUP BY 1, 2
ORDER BY 1, 2;

CALL DBT_STOCKPROJECT.DBT_DEV_STAGING.STOCK_SPROC('2026-02-20', '2026-04-04');

-- Row count per ticker per day
SELECT ticker, date, COUNT(*) AS n
FROM DBT_STOCKPROJECT.DBT_DEV_STAGING.STG_STOCKPRICE
WHERE date BETWEEN '2026-02-20' AND '2026-04-04'
GROUP BY ticker, date
ORDER BY date, ticker
LIMIT 100;

-- Total rows and distinct tickers
SELECT 
    COUNT(*)            AS total_rows,
    COUNT(DISTINCT ticker) AS distinct_tickers,
    MIN(date)           AS earliest_date,
    MAX(date)           AS latest_date
FROM DBT_STOCKPROJECT.DBT_DEV_STAGING.STG_STOCKPRICE
WHERE date BETWEEN '2026-02-20' AND '2026-04-04';


select * from DBT_STOCKPROJECT.DBT_DEV_STAGING.STG_STOCKPRICE where date >= '2026-02-20';

select * from INDUSTRYBASED_ECONOMIC_LEADING_INDICATORS.PUBLIC.INDUSTRY_LEADING_INDICATORS_TIMESERIES order by date desc limit 25;

CREATE TABLE DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_METADATA (
    INDICATORID     VARCHAR,
    AGGREGATE       VARCHAR,
    COUNT           NUMBER,
    CREATED         TIMESTAMP_NTZ,
    DESCRIPTION     VARCHAR,
    ENDTIME         TIMESTAMP_NTZ,
    FREQUENCY       VARCHAR,
    LASTMODIFIED    TIMESTAMP_NTZ,
    NAME            VARCHAR,
    SOURCE          VARCHAR,
    SEASONALITY     VARCHAR,
    STARTTIME       TIMESTAMP_NTZ,
    TYPE            VARCHAR,
    UNITS           VARCHAR,
    NOTES           VARCHAR,
    TAGS            VARCHAR,
    CALCULATION     VARCHAR,
    CITATION        VARCHAR,
    CLASSIFICATION  VARCHAR,
    INDUSTRYLIST    VARCHAR
);

CREATE TABLE DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_TIMESERIES(
    INDICATORID     VARCHAR,
    DATE            DATE,
    VALUE           FLOAT
);
select * from DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_TIMESERIES limit 10;

INSERT INTO DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_METADATA
SELECT
    INDICATORID,
    AGGREGATE,
    COUNT,
    CREATED,
    DESCRIPTION,
    ENDTIME,
    FREQUENCY,
    LASTMODIFIED,
    NAME,
    SOURCE,
    SEASONALITY,
    STARTTIME,
    TYPE,
    UNITS,
    NOTES,
    TAGS,
    CALCULATION,
    CITATION,
    CLASSIFICATION,
    INDUSTRYLIST
FROM industrybased_economic_leading_indicators.public.industry_leading_indicators_metadata;

INSERT INTO DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_TIMESERIES
SELECT
    INDICATORID,
    DATE,
    VALUE
FROM industrybased_economic_leading_indicators.public.industry_leading_indicators_timeseries;

SELECT
    INDICATORID,
    DATE,
    VALUE
FROM industrybased_economic_leading_indicators.public.industry_leading_indicators_timeseries;


CREATE OR REPLACE TASK refresh_indicator_metadata
    WAREHOUSE = DBT_STOCKPROJECT
    SCHEDULE = 'USING CRON 0 6 * * * America/New_York'
AS
MERGE INTO DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_METADATA AS target
USING industrybased_economic_leading_indicators.public.industry_leading_indicators_metadata AS source
    ON target.INDICATORID = source.INDICATORID
WHEN MATCHED THEN UPDATE SET
    target.AGGREGATE        = source.AGGREGATE,
    target.COUNT            = source.COUNT,
    target.CREATED          = source.CREATED,
    target.DESCRIPTION      = source.DESCRIPTION,
    target.ENDTIME          = source.ENDTIME,
    target.FREQUENCY        = source.FREQUENCY,
    target.LASTMODIFIED     = source.LASTMODIFIED,
    target.NAME             = source.NAME,
    target.SOURCE           = source.SOURCE,
    target.SEASONALITY      = source.SEASONALITY,
    target.STARTTIME        = source.STARTTIME,
    target.TYPE             = source.TYPE,
    target.UNITS            = source.UNITS,
    target.NOTES            = source.NOTES,
    target.TAGS             = source.TAGS,
    target.CALCULATION      = source.CALCULATION,
    target.CITATION         = source.CITATION,
    target.CLASSIFICATION   = source.CLASSIFICATION,
    target.INDUSTRYLIST     = source.INDUSTRYLIST
WHEN NOT MATCHED THEN INSERT (
    INDICATORID, AGGREGATE, COUNT, CREATED, DESCRIPTION, ENDTIME,
    FREQUENCY, LASTMODIFIED, NAME, SOURCE, SEASONALITY, STARTTIME,
    TYPE, UNITS, NOTES, TAGS, CALCULATION, CITATION, CLASSIFICATION, INDUSTRYLIST
)
VALUES (
    source.INDICATORID, source.AGGREGATE, source.COUNT, source.CREATED,
    source.DESCRIPTION, source.ENDTIME, source.FREQUENCY, source.LASTMODIFIED,
    source.NAME, source.SOURCE, source.SEASONALITY, source.STARTTIME,
    source.TYPE, source.UNITS, source.NOTES, source.TAGS, source.CALCULATION,
    source.CITATION, source.CLASSIFICATION, source.INDUSTRYLIST
);


CREATE OR REPLACE TASK refresh_indicator_timeseries
    WAREHOUSE = DBT_STOCKPROJECT
    SCHEDULE = 'USING CRON 0 6 * * * America/New_York'
AS
MERGE INTO DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_TIMESERIES AS target
USING industrybased_economic_leading_indicators.public.industry_leading_indicators_timeseries AS source
    ON target.INDICATORID = source.INDICATORID
    AND target.DATE = source.DATE
WHEN MATCHED THEN UPDATE SET
    target.VALUE = source.VALUE
WHEN NOT MATCHED THEN INSERT (INDICATORID, DATE, VALUE)
VALUES (source.INDICATORID, source.DATE, source.VALUE);

show tasks;

drop table DBT_STOCKPROJECT.DBT_DEV_STAGING.SNOWPARK_TEMP_TABLE_024TSZ19MS;
drop table DBT_STOCKPROJECT.DBT_DEV_STAGING.SNOWPARK_TEMP_TABLE_CDYNYWZSHP;

drop schema dbt_stockproject.dbt_dev;
drop schema dbt_stockproject.dbt_dev_intermediate;
drop schema dbt_stockproject.dbt_dev_staging;

drop schema dbt_stockproject.dbt_dev_table;

drop schema dbt_stockproject.intermediate;

CALL COMPANY_INFO_SPROC();

CALL DBT_STOCKPROJECT.DBT_DEV_JDS_STAGING.COMPANY_INFO_SPROC();

INSERT INTO DBT_STOCKPROJECT.PUBLIC.RAW_STOCK_DATA
SELECT
    DATE,
    OPEN,
    HIGH,
    LOW,
    CLOSE,
    ADJUSTED_CLOSE,
    VOLUME,
    DIVIDEND_AMOUNT,
    SPLIT_COEFFICIENT,
    TICKER
FROM DBT_STOCKPROJECT.DBT_DEV_JDS_STAGING.JDS_STG_STG_STOCKPRICE
WHERE DATE BETWEEN '2026-02-20' AND '2026-04-04';


-- See exact column names in both tables
DESCRIBE TABLE DBT_STOCKPROJECT.PUBLIC.RAW_STOCK_DATA;
DESCRIBE TABLE DBT_STOCKPROJECT.DBT_DEV_JDS_STAGING.JDS_STG_STG_STOCKPRICE;

-- Clear the 7 bad rows first
TRUNCATE TABLE DBT_STOCKPROJECT.PUBLIC.RAW_STOCK_DATA;

-- Copy all 140k+ rows, dropping the two DBT columns
INSERT INTO DBT_STOCKPROJECT.PUBLIC.RAW_STOCK_DATA
    (DATE, OPEN, HIGH, LOW, CLOSE, ADJUSTED_CLOSE, VOLUME, DIVIDEND_AMOUNT, SPLIT_COEFFICIENT, TICKER)
SELECT
    DATE, OPEN, HIGH, LOW, CLOSE, ADJUSTED_CLOSE, VOLUME, DIVIDEND_AMOUNT, SPLIT_COEFFICIENT, TICKER
FROM DBT_STOCKPROJECT.DBT_DEV_JDS_STAGING.JDS_STG_STG_STOCKPRICE
WHERE DATE BETWEEN '2026-02-20' AND '2026-04-04';

-- Verify
SELECT
    COUNT(*)               AS total_rows,
    COUNT(DISTINCT TICKER) AS distinct_tickers,
    MIN(DATE)              AS earliest_date,
    MAX(DATE)              AS latest_date
FROM DBT_STOCKPROJECT.PUBLIC.RAW_STOCK_DATA;

CALL DBT_STOCKPROJECT.DBT_DEV_JDS_STAGING.STOCK_SPROC('2026-02-20', '2026-04-04');

-- Drop existing regular tables
DROP TABLE IF EXISTS DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_METADATA;
DROP TABLE IF EXISTS DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_TIMESERIES;

USE ROLE ACCOUNTADMIN;

-- ---------------------------------------------------------------
-- Task 1: Refresh Metadata daily at 7 AM ET
-- ---------------------------------------------------------------
CREATE OR REPLACE TASK DBT_STOCKPROJECT.DBT_DEV_JDS_STAGING.REFRESH_INDICATORS_METADATA_TASK
    WAREHOUSE = DBT_STOCKPROJECT
    SCHEDULE  = 'USING CRON 0 7 * * * America/New_York'
AS
    CREATE OR REPLACE TABLE DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_METADATA
    AS
    SELECT *
    FROM INDUSTRYBASED_ECONOMIC_LEADING_INDICATORS.PUBLIC.INDUSTRY_LEADING_INDICATORS_METADATA;

-- ---------------------------------------------------------------
-- Task 2: Refresh Time Series daily at 7 AM ET
-- ---------------------------------------------------------------
CREATE OR REPLACE TASK DBT_STOCKPROJECT.DBT_DEV_JDS_STAGING.REFRESH_INDICATORS_TIMESERIES_TASK
    WAREHOUSE = DBT_STOCKPROJECT
    SCHEDULE  = 'USING CRON 0 7 * * * America/New_York'
AS
    CREATE OR REPLACE TABLE DBT_STOCKPROJECT.PUBLIC.RAW_INDUSTRY_LEADING_INDICATORS_TIMESERIES
    AS
    SELECT *
    FROM INDUSTRYBASED_ECONOMIC_LEADING_INDICATORS.PUBLIC.INDUSTRY_LEADING_INDICATORS_TIMESERIES;

-- ---------------------------------------------------------------
-- Resume both tasks (created suspended by default)
-- ---------------------------------------------------------------
ALTER TASK DBT_STOCKPROJECT.DBT_DEV_JDS_STAGING.REFRESH_INDICATORS_METADATA_TASK RESUME;
ALTER TASK DBT_STOCKPROJECT.DBT_DEV_JDS_STAGING.REFRESH_INDICATORS_TIMESERIES_TASK RESUME;

-- Verify
SHOW TASKS LIKE 'REFRESH_INDICATORS%' IN SCHEMA DBT_STOCKPROJECT.DBT_DEV_JDS_STAGING;