dbt_stockproject:
  outputs:
    dev:
      type: snowflake
      account: TPRFGUJ-JNC76647
      user: jdsmithwes
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: DBT_ROLE
      database: DBT_STOCKPROJECT
      warehouse: DBT_STOCKPROJECT
      schema: DBT_DEV_JDS_STAGING
      threads: 8
      client_session_keep_alive: false
      query_tag: dbt
  target: dev
