USE ROLE DBT_ROLE;
USE WAREHOUSE DBT_STOCKPROJECT;
USE DATABASE DBT_STOCKPROJECT;
USE SCHEMA DBT_DEV_JDS_STAGING;

-- Step 1: Suspend existing root tasks before restructuring
ALTER TASK STOCK_SPROC_DAILY_TASK SUSPEND;
ALTER TASK COMPANY_INFO_DAILY_TASK SUSPEND;

-- Step 2: Create a lightweight root task that owns the schedule and kicks off the DAG
CREATE OR REPLACE TASK DATA_PIPELINE_ROOT_TASK
  WAREHOUSE = DBT_STOCKPROJECT
  SCHEDULE = 'USING CRON 0 20 * * * America/New_York'
  COMMENT = 'Root task for daily data pipeline DAG - triggers at 8 PM ET'
AS
  SELECT 1;

select * from DBT_STOCKPROJECT.DBT_DEV_JDS_MARTS.JDS_MART_STOCK_PERFORMANCE_WITH_INDICATORS limit 20;

select
min(date) as starting_date,
max(date) as end_date
from DBT_STOCKPROJECT.DBT_DEV_JDS_MARTS.JDS_MART_STOCK_PERFORMANCE_WITH_INDICATORS;

-- Step 3: Recreate data-loading tasks as children of the root
CREATE OR REPLACE TASK STOCK_SPROC_DAILY_TASK
  WAREHOUSE = DBT_STOCKPROJECT
  COMMENT = 'Loads daily stock price data from AlphaVantage'
  AFTER DATA_PIPELINE_ROOT_TASK
AS
  CALL STOCK_SPROC(NULL, NULL);

CREATE OR REPLACE TASK COMPANY_INFO_DAILY_TASK
  WAREHOUSE = DBT_STOCKPROJECT
  COMMENT = 'Loads company overview data from AlphaVantage'
  AFTER DATA_PIPELINE_ROOT_TASK
AS
  CALL COMPANY_INFO_SPROC();

-- Step 4: Create dbt refresh task that runs AFTER both data tasks complete
CREATE OR REPLACE TASK DBT_REFRESH_TASK
  WAREHOUSE = DBT_STOCKPROJECT
  COMMENT = 'Refreshes all dbt models after data loading completes'
  AFTER STOCK_SPROC_DAILY_TASK, COMPANY_INFO_DAILY_TASK
AS
  EXECUTE DBT PROJECT FROM WORKSPACE USER$.PUBLIC."DBTSTOCKPROJECT_SNOWFLAKE_GITREPO"
    ARGS = 'run --target dev'
    PROJECT_ROOT = 'DBTSTOCKPROJECT';

-- Step 5: Resume tasks (children must be resumed before root)
ALTER TASK DBT_REFRESH_TASK RESUME;
ALTER TASK STOCK_SPROC_DAILY_TASK RESUME;
ALTER TASK COMPANY_INFO_DAILY_TASK RESUME;
ALTER TASK DATA_PIPELINE_ROOT_TASK RESUME;

-- Verify the DAG structure
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
  TASK_NAME => 'DATA_PIPELINE_ROOT_TASK',
  RECURSIVE => TRUE
));
