version: 2
sources:
  - name: ALPHAVANTAGE_API
    database: DBT_STOCKPROJECT
    schema: PUBLIC
    tables:
      - name: RAW_STOCK_DATA
        tests:
          - min_row_count:
              min_rows: 400
      - name: RAW_COMPANY_OVERVIEW
        tests:
          - min_row_count:
              min_rows: 400
  - name: ECONOMIC_INDICATORS
    database: INDUSTRYBASED_ECONOMIC_LEADING_INDICATORS
    schema: PUBLIC
    tables:
      - name: INDUSTRY_LEADING_INDICATORS_METADATA
      - name: INDUSTRY_LEADING_INDICATORS_TIMESERIES